management:
    context-path: /manage
    endpoint:
        info:
            enabled: true
    security:
        enabled: false

security:
    user:
        name: admin
        password: nimda

spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: pass123
        url: jdbc:mysql://localhost:3306/fajstos?useSSL=false
        username: test

    h2:
        console:
            enabled: true

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

